version: '3'

services:
  database:
    container_name: claas_db
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: claas_db
      MYSQL_ROOT_PASSWORD: claas,DB2024
      MYSQL_PASSWORD: claas,DB2024
      MYSQL_USERNAME: root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - claas_network

networks:
  claas_network:
    driver: bridge